import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const user = useUser();

  const email = user?.user?.primaryEmailAddress?.emailAddress || "UNKNOWN";

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && !user.isSignedIn ? (
        <SignInButton>
          <button className="rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700">
            Sign in
          </button>
        </SignInButton>
      ) : (
        <SignOutButton>
          <button className="rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700">
            Sign out from {email}
          </button>
        </SignOutButton>
      )}
    </>
  );
};

export default Home;
